
x-app-defaults: &app-defaults
  restart: always
  image: suhailbw/nudge:latest
  ports:
    - "9000:9000"
  networks:
    - nudge
  environment:
    - TZ=Etc/UTC

services:
  app:
    <<: *app-defaults
    container_name: nudge_app
    volumes:
      - ./config.yml:/nudge/config.yml
      - ./index.html:/nudge/static/index.html
      - ./privacy.html:/nudge/static/privacy.html
      - ./toc.html:/nudge/static/toc.html
      - ./slack-integration.html:/nudge/static/slack-integration.html

networks:
  nudge:

volumes:
  nudge-data: