services:
  db:
    image: mongo:6.0.5
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: nudge
      MONGO_INITDB_ROOT_PASSWORD: nudge
    networks:
      - nudge-dev
    restart: unless-stopped
    volumes:
      - type: volume
        source: nudge-dev-db
        target: /var/lib/nudge/data

  backend:
    build:
      context: ../
      dockerfile: dev/app.Dockerfile
    command: ["make", "run-dev-backend"]
    ports:
      - "9000:9000"
    depends_on:
      - db
    volumes:
      - ../:/nudge
    networks:
      - nudge-dev


volumes:
  nudge-dev-db:

networks:
  nudge-dev: